---
title: "NoDag Algorithm Final Testing"
output:
  html_notebook: default
  pdf_document: default
---

# Setup
```{r}
# Load packages
library(bnlearn)
library(Rgraphviz)
library(psych)
library(lavaan)
library(gnlearn)
library(igraph)
library(dplyr)
```

```{r}
# Set data file paths
data_path <- paste0(getwd(), "/data/")

ko_lsds40_biomech_path <- paste0(data_path, "LSDS-40_Bone_Biomechanical_LDSD-40_biomechanical_KoTRANSFORMED.csv")
ko_lsds40_microct_path <- paste0(data_path, "LSDS-40_microCT_LSDS-40_microCT_KoTRANSFORMED.csv")
ko_lsds451_path <- paste0(data_path, "LSDS-41_peripheral_quantitative_computed_tomography_pQCT_LSDS-41_pQCT_KoTRANSFORMED.csv")
```

# Data Cleaning
```{r}
nastring <- c("           *", "epiphysis broken") # things we want R to read as NA

# Read raw files
ko1 <- read.csv(ko_lsds40_biomech_path, header = T, stringsAsFactors = F)
ko3 <- read.csv(ko_lsds40_microct_path, header = T, stringsAsFactors = F, na.strings = nastring)
ko4 <- read.csv(ko_lsds451_path, header = T, stringsAsFactors = F)

# Subest to needed columns/rows
ko1 <- ko1[, c(1, 3:4, 8:10)]
ko3 <- ko3[, c(1, 10, 13:17)]
ko4 <- ko4[, c(1, 4:7)]

# Rename columns
names(ko1) <- c("ID", "PWB", "duration", "stiffness", "load.max", "load.fail")
names(ko3) <- c("ID", "BVTV", "trab.num", "trab.thick", "trab.sep", "BMD", "cort.thick")
names(ko4) <- c("ID", "BMD0", "BMD1", "BMD2", "BMD4")

# Create indicators of source file
ko1$k1 <- 1
ko3$k3 <- 1
ko4$k4 <- 1

# Merge files
ko13 <- merge(ko1, ko3, by = "ID", all = T)
ko134 <- merge(ko13, ko4, by = "ID", all = T)

# Fill in missing indicators with 0
ko134$k1[is.na(ko12$k1)] <- 0
ko134$k3[is.na(ko12$k3)] <- 0
ko134$k4[is.na(ko12$k4)] <- 0

# Keep only needed rows
ko <- ko134[!(is.na(ko134$stiffness)), ]
ko <- ko[ko$PWB %in% c("PWB100", "PWB20") & ko$duration %in% c("2wk", "4wk"), ]

# Create unload column
ko$unload <- (ko$PWB != "PWB100") * 1

# Convert to numeric
ko <- as.data.frame(sapply(ko, as.numeric))
```

# Au Naturel
```{r}
ko_naturel <- ko[, c("unload", "BVTV", "BMD", "trab.sep", "trab.num", "load.max", "load.fail")]

ko_naturel_dag <- nodag(ko_naturel)

plot(ko_naturel_dag)
```

# PCA-synthetic
```{r}
mass <- pca(r = ko[, c("BVTV", "BMD")], nfactors = 1, scores = T)
trab <- pca(r = ko[, c("trab.sep", "trab.num")], nfactors = 1, scores = T)
stren <- pca(r = ko[, c("load.max", "load.fail")], nfactors = 1, scores = T)

ko_pca <- ko

ko_pca$mass <- as.vector(mass$scores[, 1])
ko_pca$trab <- as.vector(trab$scores[, 1])
ko_pca$stren <- as.vector(stren$scores[, 1])

ko_pca <- ko_pca[, c("unload", "mass", "trab", "stren")]

rm(list = c("mass", "trab", "stren"))

ko_pca_dag <- nodag(ko_pca)

plot(ko_pca_dag)
```

