---
title: "NoDag"
output:
  html_notebook: default
  pdf_document: default
---

This notebook aims to explore the potential applications of [NoDag](https://doi.org/10.48550/arXiv.2006.03005).

## Setup
```{r}
# Install packages
# install.packages("bnlearn")
# install.packages("BiocManager")
# BiocManager::install("Rgraphviz")
# install.packages(c("psych", "lavaan"), dependencies = TRUE)
# remotes::install_github("rlebron-bioinfo/gnlearn")
# install.packages("mice")
# install.packages("ggplot2")
# install.packages("GeneNet")
# install.packages("igraph", dependencies = TRUE)
```

```{r}
# Load packages
library(bnlearn)
library(Rgraphviz)
library(psych)
library(lavaan)
library(gnlearn)
library(mice)
library(GeneNet)
library(igraph)
```

```{r}
# Set data file paths
# setwd("../")
data_path <- paste0(getwd(), "/data/")

alwood_lsds15_path <- paste0(data_path, "LSDS-15_microCT_alwoodTRANSFORMED.csv")
ko_lsds40_biomech_path <- paste0(data_path, "LSDS-40_Bone_Biomechanical_LDSD-40_biomechanical_KoTRANSFORMED.csv")
ko_lsds40_histo_path <- paste0(data_path, "LSDS-40_histomorphometry_LSDS-40_histomorphometry_KoTRANSFORMED.csv")
ko_lsds40_microct_path <- paste0(data_path, "LSDS-40_microCT_LSDS-40_microCT_KoTRANSFORMED.csv")
ko_lsds451_path <- paste0(data_path, "LSDS-41_peripheral_quantitative_computed_tomography_pQCT_LSDS-41_pQCT_KoTRANSFORMED.csv")
turner_glds351_path <- paste0(data_path, "GLDS-351.csv")
turner_lsds30_path <- paste0(data_path, "LSDS-30_histomorphometry_turnerTRANSFORMED.csv")
```

## Data preprocessing and formatting

### Alwood LSDS-15
```{r}
alwood <- read.csv(alwood_lsds15_path, header = T, stringsAsFactors = F)
alwood <- alwood[11:37, c(3:6, 9)]
alwood$expose <- ifelse(alwood$Factor.Value == "Flight", 1, 0)
names(alwood)[2:5] <- c("thick", "sep", "num", "bvtv")

trab <- pca(r = alwood[, c("sep", "num")], nfactors = 1, scores = T)
mass <- pca(r = alwood[, c("thick", "bvtv")], nfactors = 1, scores = T)

alwood$trab <- as.vector(trab$scores)
alwood$mass <- as.vector(mass$scores)

alwood <- alwood[, c("expose", "trab", "mass")]

rm(list = c("trab", "mass"))
```

### Ko LSDS-40 and LSDS-451
```{r}
nastring <- c("           *", "epiphysis broken") # things we want R to read as NA

# Read raw files
ko1 <- read.csv(ko_lsds40_biomech_path, header = T, stringsAsFactors = F)
ko2 <- read.csv(ko_lsds40_histo_path, header = T, stringsAsFactors = F, na.strings = nastring)
ko3 <- read.csv(ko_lsds40_microct_path, header = T, stringsAsFactors = F, na.strings = nastring)
ko4 <- read.csv(ko_lsds451_path, header = T, stringsAsFactors = F)

# Subest to needed columns/rows
ko1 <- ko1[, c(1, 3:4, 8:10)]
ko2 <- ko2[!(is.na(ko2$Source.Name)), c(1, 7:11)]
ko3 <- ko3[, c(1, 10, 13:17)]
ko4 <- ko4[, c(1, 4:7)]

# Rename columns
names(ko1) <- c("ID", "PWB", "duration", "stiffness", "load.max", "load.fail")
names(ko2) <- c("ID", "OBSBS", "OCSBS", "MSBS", "MAR", "BFRBS")
names(ko3) <- c("ID", "BVTV", "trab.num", "trab.thick", "trab.sep", "BMD", "cort.thick")
names(ko4) <- c("ID", "BMD0", "BMD1", "BMD2", "BMD4")

# create indicators of source file
ko1$k1 <- 1
ko2$k2 <- 1
ko3$k3 <- 1
ko4$k4 <- 1

# Merge files
ko12 <- merge(ko1, ko2, by = "ID", all.x = T, all.y = T)
ko123 <- merge(ko12, ko3, by = "ID", all = T)
ko1234 <- merge(ko123, ko4, by = "ID", all = T)

# Fill in missing indicators with 0
ko1234$k1[is.na(ko12$k1)] <- 0
ko1234$k2[is.na(ko12$k2)] <- 0
ko1234$k3[is.na(ko12$k3)] <- 0
ko1234$k4[is.na(ko12$k4)] <- 0

# Keep only needed rows
ko <- ko1234[!(is.na(ko1234$stiffness)), ]
ko$unload <- 0 * (ko$PWB == "PWB100") + 30 * (ko$PWB == "PWB70") + 60 * (ko$PWB == "PWB40") + 80 * (ko$PWB == "PWB20")
ko$dur <- 7 * (ko$duration == "1wk") + 14 * (ko$duration == "2wk") + 28 * (ko$duration == "4wk")
ko <- ko[, c("BVTV", "BMD", "trab.sep", "trab.num", "MSBS", "OCSBS", "BFRBS", "load.max", "load.fail", "unload", "dur")]

# Convert to numeric
ko <- as.data.frame(sapply(ko, as.numeric))

# Subset to data from 4 week duration and either 0%, 60%, or 80% unloaded
# ko <- ko[ko$dur == 28, ]
# ko <- ko[ko$unload %in% c(0, 60, 80), ]

mass <- pca(r = ko[, c("BVTV", "BMD")], nfactors = 1, scores = T)
trab <- pca(r = ko[, c("trab.sep", "trab.num")], nfactors = 1, scores = T)
form <- pca(r = ko[, c("MSBS", "BFRBS")], nfactors = 1, scores = T)
stren <- pca(r = ko[, c("load.max", "load.fail")], nfactors = 1, scores = T)

ko$mass <- as.vector(mass$scores[, 1])
ko$trab <- as.vector(trab$scores[, 1])
ko$stren <- as.vector(stren$scores[, 1])
ko$expose <- ((ko$unload * ko$dur) - mean(ko$unload * ko$dur)) / (sd(ko$unload * ko$dur))
ko$resorp <- scale(ko$OCSBS)
ko$form <- as.vector(form$scores)

ko <- ko[, c("dur", "unload", "expose", "mass", "trab", "stren", "resorp", "form")]

rm(list = c("mass", "trab", "form", "stren"))
```

```{r}
# Create a copy of the original data frame for imputation
ko_imputed <- ko

# Perform mean imputation on the columns with missing values
ko_imputed$resorp <- ifelse(is.na(ko$resorp), mean(ko$resorp, na.rm = TRUE), ko$resorp)
ko_imputed$form <- ifelse(is.na(ko$form), mean(ko$form, na.rm = TRUE), ko$form)
```

```{r}
# Subset to data from 4 week duration
ko_4week <- ko_imputed[ko_imputed$dur == 28, ]
ko_4week <- ko_4week[, c("expose", "mass", "trab", "stren", "resorp", "form")]

# Subset to data from 2 week duration
ko_2week <- ko_imputed[ko_imputed$dur == 14, ]
ko_2week <- ko_2week[, c("expose", "mass", "trab", "stren", "resorp", "form")]

# Subset to data from 1 week duration
ko_1week <- ko_imputed[ko_imputed$dur == 7, ]
ko_1week <- ko_1week[, c("expose", "mass", "trab", "stren", "resorp", "form")]

# Remove dur and unload columns
ko_all <- ko_imputed[, c("expose", "mass", "trab", "stren", "resorp", "form")]

# Add exposure variable equal to duration*unload
ko_exposure <- ko_all
ko_exposure$exposure <- ko_imputed$dur * ko_imputed$unload
```

### Turner GLDS-30
```{r}
glds <- read.csv(turner_glds351_path, header = T, stringsAsFactors = F)
glds$expose <- ifelse(glds$Teatment == "Ground Control", 0, 1)
glds <- glds[7:30, c(5:7, 11, 13, 16:19, 22:25)]

# Make component variables
mass <- pca(r = glds[, c("DXA_BMC_mg", "DXA_BMD_mg_per_mmsq")], nfactors = 1, scores = T)
trab_meta <- pca(r = glds[, c("metaphysis_canc_Tb_Sp_micrometer", "metaphysis_canc_Tb_N_1per_mm")], nfactors = 1, scores = T)
trab_epiph <- pca(r = glds[, c("epiphysis_canc_Tb_Sp_micrometer", "epiphysis_canc_Tb_N_1per_mm")], nfactors = 1, scores = T)

glds$mass <- as.vector(mass$scores)
glds$trab_meta <- as.vector(trab_meta$scores)
glds$trab_epiph <- as.vector(trab_epiph$scores)

# Standardize site-specific/single variable mass measures
names(glds)[5] <- "mass_meta"
glds$mass_meta <- scale(glds$mass_meta)

names(glds)[9] <- "mass_epiph"
glds$mass_epiph <- scale(glds$mass_epiph)

# Final dataset
glds <- glds[, c("expose", "mass", "mass_meta", "mass_epiph", "trab_meta", "trab_epiph")]

rm(list = c("mass", "trab_epiph", "trab_meta"))
```

```{r}
# Subset data to only expose, mass_meta, and trab_meta
glds_meta <- glds[, c("expose", "mass_meta", "trab_meta")]

# Subset data to only expose, mass_epiph, and trab_epiph
glds_epiph <- glds[, c("expose", "mass_epiph", "trab_epiph")]

# Subset data to only expose, mass_meta, trab_meta, mass_epiph, and trab_epiph
glds_meta_epiph <- glds[, c("expose", "mass_meta", "trab_meta", "mass_epiph", "trab_epiph")]
```

### Turner LSDS-30
```{r}
turner <- read.csv(turner_lsds30_path, header = T, stringsAsFactors = F)
turner <- turner[, c(1, 3:9)]
turner$expose <- ifelse(turner$Spaceflight == "Space Flight", 1, 0)
names(turner)[3:8] <- c("mass", "labellength", "cont_bf", "ceased_bf", "MAR", "osteoc_per")

# Create measures
resorp <- pca(r = turner[, c("labellength", "osteoc_per")], nfactors = 1, scores = T)
form <- pca(r = turner[, c("ceased_bf", "MAR")], nfactors = 1, scores = T)

turner$resorp <- as.vector(resorp$scores)
turner$form <- as.vector(form$scores) * -1 ## form loads "backwards"; multiply by -1 to fix
turner$mass <- scale(turner$mass)

turner <- turner[, c(9, 3, 10:11)]
rm(list = c("form", "resorp"))
```

### Correlation Matrices
```{r}
cor(alwood)

cor(glds)
cor(glds_meta)
cor(glds_epiph)
cor(glds_meta_epiph)

cor(ko_4week)
cor(ko_2week)
cor(ko_1week)
cor(ko_all)
cor(ko_exposure)

cor(turner)
```

## NoDag
```{r}
# Call nodag on dfs
alwood_dag <- nodag(alwood)

glds_dag <- nodag(glds)
glds_meta_dag <- nodag(glds_meta)
glds_epiph_dag <- nodag(glds_epiph)
glds_meta_epiph_dag <- nodag(glds_meta_epiph)

ko_4week_dag <- nodag(ko_4week)
ko_2week_dag <- nodag(ko_2week)
ko_1week_dag <- nodag(ko_1week)
ko_all_dag <- nodag(ko_all)
ko_exposure_dag <- nodag(ko_exposure)

turner_dag <- nodag(turner)

# Plot DAGs
plot(alwood_dag)
title("Alwood (NoDag)")

plot(ko_4week_dag)
title("Ko 4 Weeks (NoDag)")
plot(ko_2week_dag)
title("Ko 2 Weeks (NoDag)")
plot(ko_1week_dag)
title("Ko 1 Week (NoDag)")
plot(ko_all_dag)
title("Ko (NoDag)")
plot(ko_exposure_dag)
title("Ko with Exposure (NoDag)")

plot(glds_dag)
title("Turner GLDS-351 (NoDag)")
plot(glds_meta_dag)
title("Turner GLDS-351 Meta (NoDag)")
plot(glds_epiph_dag)
title("Turner GLDS-351 Epiph (NoDag)")
plot(glds_meta_epiph_dag)
title("Turner GLDS-351 Meta and Epiph (NoDag)")

plot(turner_dag)
title("Turner LSDS-30 (NoDag)")
```
